version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: app_container
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URI: "mongodb://mongo:27017/schoolDB"
    restart: always

volumes:
  mongo_data:
