apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80    # Ingress will forward traffic here
      targetPort: 3000  # App container is listening on port 3000