name: CI Pipeline for Dockerized App

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t keriot/proekt_kontinuirana-app:${{ github.sha }} -t keriot/proekt_kontinuirana-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push keriot/proekt_kontinuirana-app:${{ github.sha }}
          docker push keriot/proekt_kontinuirana-app:latest

      - name: Logout from Docker Hub
        run: docker logout
